### ISSUE TITLE
[1.15pre6] Advanced Tooltips (f3+h) breaking tooltips

### ISSUE THREAD

**Issue by zeflap** [TechReborn/TechReborn#1905] opened 2019-12-10 08:17 UTC
Normal (f3+h not enabled):
![1575965647](https://user-images.githubusercontent.com/4191012/70507839-e2c50200-1b35-11ea-9e0d-5ce834c1db62.png)
Advanced[ha] (f3+h enabled):
![1575965697](https://user-images.githubusercontent.com/4191012/70507918-05571b00-1b36-11ea-8634-87c6e65ae33c.png)
This happens with any TR item, and it's rather annoying to have to toggle it every so often.

**Comment by modmuss50** [comment] 2019-12-11 15:03
![](https://ss.modmuss50.me/java_2019-12-11_15-02-35.png)

humm, I cannot reproduce this.

**Comment by modmuss50** [comment] 2019-12-11 21:00
Casuse of this is another mod, closing here.

**Closed as completed by modmuss50** 2019-12-11 21:00 UTC
