### ISSUE TITLE
server crash, ticking world entity

### ISSUE THREAD

**Issue by TheDarkPreacher** [TechReborn/TechReborn#1564] opened 2018-07-01 17:26 UTC
Version: 1.12.2-2.16.0.746-universal
Forge: 14.23.4.2705

Server running Coop Life 2, crashed and gave this crash report: https://pastebin.com/RYFFubax

Server gave this crash report immediately preceding the ticking world entity: https://pastebin.com/LAZndHfy 

will pass on second paste to Refined Storage team with link back to this report.

**Comment by modmuss50** [comment] 2018-07-02 10:59
Wrong issue tracker + I have no idea what is going on. raoulvdberge said it is fixed in the next update, My guess is the crash was caused by not being able to save the multiblock correctly when the server crashed.

**Closed as completed by modmuss50** 2018-07-02 10:59 UTC
