### ISSUE TITLE
invisible machineblocks glitch/bug

### ISSUE THREAD

**Issue by RakDuhl** [TechReborn/TechReborn#749] opened 2016-09-18 12:03 UTC
My problem is that the standart, reinforced and advanced machine casings dont have a atexture, instead are straight invisible. i do not know if i'm the only person that experience this problem, but i have it...

[http://i.imgur.com/jw0ujaV.png](url)

**Comment by modmuss50** [comment] 2016-09-18 12:03
Dupe of: https://github.com/TechReborn/TechReborn/issues/741

**Closed as completed by modmuss50** 2016-09-18 12:03 UTC
