### ISSUE TITLE
(Don't know if bug or feature) I can't grind raw iron ore ?

### ISSUE THREAD

**Issue by Raavea** [TechReborn/TechReborn#2463] opened 2021-07-31 06:54 UTC
**Describe the bug**
Apologies, I'm yet to figure out if it's a bug or an intentional decision. 
Basically, your mod is literally the only tech mod available for a (private)pack I have put together for myself and my partner to play - they've never played minecraft on PC, and never played modded minecraft - and it sounded pretty good; all in one, yes please (no messing around with incompatibilities between machines !).
The issue is that your mod requires an absolutely incredible amount of iron, yet does not seem to grind raw iron (or copper, or gold) into dusts. That is, there is absolutely No Ore Doubling. This means that unless I spend hours grinding away mining for ore, I can't progress in your mod, which means my partner won't be interested in it either. And it seemed like such a good opportunity!
(Also, thanks for bringing your wiki back online, it's been a nightmare having no reference.)

TL,DR: I can't grind raw iron ore (to double it) and I don't know if bug or intentional feature

**Steps to Reproduce**
- Get raw iron ore
- Stuff it in grinder
- Observe absolutely nothing happening

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17
 - Mod Loader: Fabric (latest?)
 - (I use the curseforge launcher)

**Logs**
I don't think there is anything relevant in my logs.

**Comment by Ayutac** [comment] 2021-07-31 13:26
The iron doubling is now a Vanilla feature when you mine an Ore Block. Just enchant your pickaxe with fortune as you would for diamonds eventually.

**Comment by drcrazy** [comment] 2021-07-31 23:12
You can grind ore blocks. And there is a https://wiki.techreborn.ovh/doku.php?id=items:rock_cutter to get it. Maybe we should change recipe for it to be obtainable earlier.

**Comment by arslan2012** [comment] 2021-08-01 06:09
duplicate of https://github.com/TechReborn/TechReborn/issues/2422

**Comment by Raavea** [comment] 2021-08-02 06:54
I feared this would be the case. Any chance you could add this as a toggle option in the mod settings? I don't actually ever enchant my gear for diamonds; my partner and I just play to build cool stuff and explore; any enchanted gear is only things we find in dungeons etc - it makes it more rewarding. I've not really bothered with enchantments since I started playing (and that was in 2007 - I don't think enchantments even existed then, though). I can't be the only person?

ETA: I see the rock cutter basically is a silk touch pickaxe, and I'll give it a go, though I prefer to use an [obsidian] excavator hammer and then only get my pickaxe out for tasty ore/gem nodes.

**Closed as completed** 2021-08-13 22:11 UTC
Labels: bug
