### ISSUE TITLE
Missing Recipes in JEI

### ISSUE THREAD

**Issue by VermillionX** [TechReborn/TechReborn#1431] opened 2018-02-04 02:46 UTC
Simple enough. Mixed Metal Ingots do not have a recipe in JEI, yet the recipes are definitely there and working.
Using latest version.
EDIT: Actually, It's all TechReborn crafting recipes. None of them are showing up in JEI. Recipes involving TR machines are working, but ones involving shaped or shapeless recipes are not.

**Comment by access-ible** [comment] 2018-02-04 16:18
I've been working with VermillionX to identify the root cause. 
It seems to be a side effect of updating other mods.
Please wait for more information before pursuing this issue. Thank you.

**Comment by modmuss50** [comment] 2018-02-04 16:19
Interesting, let me know if there is anything you want me to take a look at.

**Comment by access-ible** [comment] 2018-02-04 17:45
Root cause is Custom NPCs mod.
Tested with version CustomNPCs_1.12.2(20jan18).

Can reliably cause and repair the problem by enabling/disabling only the Custom NPCs mod.
I never would have suspected Custom NPCs.

**Comment by modmuss50** [comment] 2018-02-04 17:53
Interesting, I will see if I can reproduce it

**Comment by access-ible** [comment] 2018-02-04 17:56
I should add that we had not used Custom NPCs before, so I'm unsure how far back in Custom NPCs releases this can be reproduced.

**Comment by modmuss50** [comment] 2018-02-04 18:00
![java_2018-02-04_17-59-31](https://user-images.githubusercontent.com/4324090/35780560-33a89fd4-09d5-11e8-8bde-c437aa1ca7e5.png)

Using latest TechReborn (from source)
and CustomNPCs_1.12.2(20jan18).jar

**Comment by access-ible** [comment] 2018-02-04 18:11
It's not just recipes for Tech Reborn that aren't shown, I've seen Immersive Engineering crafting recipes not shown as well. 

But this is interesting, perhaps there is an interaction with some other core mod that occurs when Custom NPCs is present.

I can try keeping TechReborn and Custom NPCs while disabling other mods, I'll start with core mods.

**Comment by access-ible** [comment] 2018-02-04 19:19
I could have been more clear.
I don't believe this is a Tech Reborn bug in any way whatsoever. The recipes of other mods also do not display in JEI.

**Comment by modmuss50** [comment] 2018-02-04 19:19
Ok, ill close this issue. Feel free to open another issue if you find any more issues with tr.

**Closed as completed by modmuss50** 2018-02-04 19:19 UTC
Labels: bug
