### ISSUE TITLE
Crash when not using 16x texture pack

### ISSUE THREAD

**Issue by MrBretze** [TechReborn/TechReborn#201] opened 2015-10-23 04:14 UTC
log: http://hastebin.com/olucojavop.tex

juste reload the resource pack

**Comment by modmuss50** [comment] 2015-10-23 13:57
Did you have a resource pack installed?

**Comment by modmuss50** [comment] 2015-10-23 13:57
Or a different resolution one?

**Comment by MrBretze** [comment] 2015-10-23 14:09
I have tested to installed the faithful resource pack in 32x32 dimension

**Comment by MrBretze** [comment] 2015-10-23 14:10
My try catch fix this, i dont no why

**Comment by modmuss50** [comment] 2015-10-23 14:39
It would, but that will break the lesu connected textures

**Comment by modmuss50** [comment] 2015-10-23 14:56
The issue is when the textures are a different size. It is using a 32x32 lapis texture, with a 16x16 boarder

**Comment by modmuss50** [comment] 2015-10-23 15:02
I've pulled your fix, but I need to get a proper fix for this, as now the connected textures for the lesu will be broken

**Closed** 2015-11-01 16:27 UTC
Labels: bug
