### ISSUE TITLE
[1.16.3] Ores doesn't break even with a Diamond Pickaxe

### ISSUE THREAD

**Issue by Desempregago** [TechReborn/TechReborn#2230] opened 2020-09-25 14:40 UTC
**Describe the bug**
Ores were supposed to break and drop their respective resources, but they simply vanish after breaking, as if they were mined with a tool with a mining level lower than needed

**Steps to Reproduce**
Mine an ore with any pickaxe

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.3
 - Mod Loader: Fabric v0.9.3-b207, with Fabric API v0.21.0-b407
 - RebornCore: v4.4.2-b73
 - Tech Reborn: v3.5.4-b122

I've tested in 2 environments: One with more mods loaded (70+ mods), and one with only TechReborn, RebornCore and the Fabric API. It happens in both environments.

**Comment by R3DRUMVNE** [comment] 2020-09-26 17:53
[Check this](https://imgur.com/a/0ruCbVi). There are three levels into which ores are divided:

1. ores that break with a stone pickaxe (or higher): coal ore, lapis lazuli ore, nether quartz ore, tin ore, bauxite ore, copper ore and iron ore;

2. ores that break with an iron pickaxe (or higher): cinnabar ore, sphalerite ore, galena ore, lead ore, silver ore, ruby ore, sapphire ore, gold ore, emerald ore, diamond ore, redstone ore and nether gold ore;

3. ores that break with a diamond pickaxe (or higher): iridium ore, peridot ore, pyrite ore, sheldonite ore, tungsten ore and sodalite ore.

This is not a bug.

**Comment by Desempregago** [comment] 2020-09-26 19:16
I tested it with a DIamond and a Netherite pickaxe, and even Copper Ore didn't break

**Comment by R3DRUMVNE** [comment] 2020-09-27 05:12
I dont know. I tried to break the copper ore with a diamond pickaxe and it worked. The ore dropped out to me. I have the same version of the fabric mod loader, fabric api, tech reborn and reborn core.

**Comment by Desempregago** [comment] 2020-09-27 20:44
Update: I found the cause of the problem. If you disable Gem Tools and Armor in the config file, the ores stop being "minable" (won't drop)

**Comment by R3DRUMVNE** [comment] 2020-10-02 14:37
> 
> 
> Update: I found the cause of the problem. If you disable Gem Tools and Armor in the config file, the ores stop being "minable" (won't drop)

Close the issue

**Closed as completed** 2020-10-02 16:00 UTC
Labels: bug
