### ISSUE TITLE
Infinite Flight

### ISSUE THREAD

**Issue by Lildude726** [TechReborn/TechReborn#3080] opened 2022-11-30 19:07 UTC
This was done on the AoF6 EU server on 0.1.7
All you have to do is have a quantum chestplate in your inv, and you can fly.
If you go to a different dimension or leave the server it'll stop it but you just have to get a quantum chestplate again.
I was told to report this bug here.

**Comment by Ayutac** [comment] 2022-12-04 18:05
cannot reproduce

**Comment by armadaazteca** [comment] 2022-12-25 02:04
It looks like the expected behavior, you get "Creative mode" flight, jump twice quickly to stop flying, but, every time you jump or double jump you will be in that mode again. It would be nice to disable this feature from the chesplate, but afaik its not possible.

**Comment by modmuss50** [comment] 2023-06-25 10:33
I think this bug was fixed by https://github.com/TechReborn/TechReborn/commit/ba99161222dc7670334b5e72869f5e59d949ad39

**Closed as completed by modmuss50** 2023-06-25 10:33 UTC
Labels: bug
