### ISSUE TITLE
Server Crash Standalone  (0.5.1.879)

### ISSUE THREAD

**Issue by parcel31u** [TechReborn/TechReborn#174] opened 2015-10-07 22:44 UTC
http://pastebin.com/u5A5eWW1

**Comment by modmuss50** [comment] 2015-10-08 06:50
this is a dupe of https://github.com/TechReborn/TechReborn/issues/161

If you want to you can use a jenkins build from here, http://modmuss50.me:8080/job/TechReborn/

I will push an update to curse soon with a handfull of fixes.

**Closed by modmuss50** 2015-10-08 06:50 UTC
Labels: bug, duplicate, High priority
