### ISSUE TITLE
[1.19] BGY Compat

### ISSUE THREAD

**Issue by MSandro** [TechReborn/TechReborn#2978] opened 2022-06-10 06:44 UTC
**Describe the bug**
Can not create or load a world.

**Steps to Reproduce**
- install RebornCore + TechReborn + BGY
- create a new world

**Environment (please complete the following information with the version):**
 - Minecraft: 1.19
 - Mod Loader: FABRIC 0.14.7

**Logs**
https://bytebin.lucko.me/vzgN4yQfLF

**Comment by Ayutac** [comment] 2022-06-10 06:58
Duplicate of #2976

**Closed as completed by Ayutac** 2022-06-10 06:58 UTC
Labels: bug, duplicate
