### ISSUE TITLE
Mod makes spectator mode impractical (ores don't blend in with stone)

### ISSUE THREAD

**Issue by Mach12** [TechReborn/TechReborn#737] opened 2016-09-06 20:36 UTC
As little of a problem as it is, when you go through the world in spectator mode, TechReborn ores are the only ones that will stick out, instead of blending in with the rest of the terrain, when you clip in a wall.

It's not much outside of spectator mode, so it's not a big deal but seriously this:

![2016-09-06_22 30 51](https://cloud.githubusercontent.com/assets/3253035/18290021/12995368-7482-11e6-804b-997d23300109.png)

That's just nasty. So many ores that obstruct your view, you could miss entire caves just because ores were in the way.

(Yea you can't see too much on the screenshot, sorry. That's the best I could get on max brightness, night vision and hidden HUD.)

**Comment by modmuss50** [comment] 2016-09-06 20:37
dupe of : https://github.com/TechReborn/TechReborn/issues/675

**Closed as completed by modmuss50** 2016-09-06 20:37 UTC

**Comment by modmuss50** [comment] 2016-09-06 20:46
Fixed: https://github.com/modmuss50/JSON-Destroyer/commit/b6ce407a1a11df99decf8c111bf037206fe009d7
