### ISSUE TITLE
Power not syncing in SMP

### ISSUE THREAD

**Issue by DoughnutDev** [TechReborn/TechReborn#703] opened 2016-07-31 05:43 UTC
I am running the latest version of TechReborn but when setting up power gen. When it hits 30 thousand EU it goes negative in the MFE and it also does this with the bat box from what I am seeing. Here is a pic of what it looks like https://gyazo.com/b440c2b5bcce4d01fc0bd0dbc7fe9ea3

**Comment by PrincessOfEvil** [comment] 2016-07-31 05:45
Use WAILA. All GUIs are broken in some way.

**Comment by DoughnutDev** [comment] 2016-07-31 16:54
Will be fixed in future releases?

**Comment by Dragon2488** [comment] 2016-07-31 17:18
Of course not. We love bugs.

**Comment by modmuss50** [comment] 2016-08-01 09:20
Dupe of: https://github.com/TechReborn/TechReborn/issues/565

Has it been fixed in dev versions?

**Comment by Dragon2488** [comment] 2016-08-01 13:52
I don't know.

**Comment by DoughnutDev** [comment] 2016-08-01 15:45
No

**Comment by modmuss50** [comment] 2016-08-08 15:39
Ok I know whats up with this.

**Comment by modmuss50** [comment] 2017-01-10 19:26
Fixed in 1.11.2, should be backported.

**Closed as completed by modmuss50** 2017-01-10 19:26 UTC
Labels: bug
