### ISSUE TITLE
Server Crashing while starting when using OpenJ9 JVM

### ISSUE THREAD

**Issue by Taviala** [TechReborn/TechReborn#1673] opened 2019-02-25 18:02 UTC
Playing the new FTB Ultimate Reloaded pack and wanted to run it on my Server. Without TechReborn the server works perfectly, but as soon as i add it back the Server crashes upon startup.

TechReborn-1.12.2-2.20.12.937-universal
RebornCore-1.12.2-3.13.4.419-universal

[crash-2019-02-25_18.48.49-server.txt](https://github.com/TechReborn/TechReborn/files/2901838/crash-2019-02-25_18.48.49-server.txt)

I added the Latest Crash report too.
I hope it's a fault on my end.

**Comment by modmuss50** [comment] 2019-02-25 18:03
Humm, ive not seen this one before, not really sure what is causing this.

**Comment by Taviala** [comment] 2019-02-25 18:07
The funny thing is that it works perfectly fine in Single Player, but as soon as i try to start the Server with the exact same mods it crashes with said Crash Report. Just wanted to bring that one to your attention in case somebody else might experience the same error.

**Comment by modmuss50** [comment] 2019-02-25 18:08
Yeah, this is very strange, I my self have played quite a bit on an multiplayer ultimate server without issue.

Only thing I see from the crash log is that you are using `Eclipse OpenJ9` and not the standard hotspot JVM, has this just started happening after you updated/changed JVM, or is this the first time you are installing this mod pack on the server?

**Comment by Taviala** [comment] 2019-02-25 18:11
I just installed it on the Server, to be more accurate i let it be installed on the Server, but i myselfe don't really have any Experience concerning Java etc.

**Comment by modmuss50** [comment] 2019-02-25 18:12
Yes, can confirm its an issue with the OpenJ9 JVM, Hotspot is known to work.

Did you install java on this server? Or did it come pre-installed.

**Comment by Taviala** [comment] 2019-02-25 18:13
It did come pre-installed, i just had to select what Modpack i wanted to install (never had any problems before).

**Comment by modmuss50** [comment] 2019-02-25 18:15
Ok, I can reproduce the issue on my computer, its going to take some investigating.

Depending on who runs your server you can either switch to Hotspot (Much more widely used/shipped with MC). (see https://adoptopenjdk.net/)

I would like to support this, but its an interesting bug so it may take me a bit to get my head around what is causing it.

**Comment by Taviala** [comment] 2019-02-25 18:16
Glad i could deliver something interesting and thanks for the fast help.

**Comment by modmuss50** [comment] 2019-02-25 18:42
Ok, I think ive tracked it down, this JVM doesn't make some assumptions that we relied on with Hot Spot.

I believe the issue is to do with `String.ToLowerCase()`


In HS if the string is already lowercase it returns the same instance of the string.

In J9 it returns a __new__ instance, this breaks some bad code we have. A fix for this is to use String.intern after we use `.ToLowerCase()`. I will build a test version of RebornCore for you to try with to see if it has been fixed.

**Comment by modmuss50** [comment] 2019-02-25 18:46
https://jenkins.modmuss50.me/job/Team%20Reborn/job/RebornCore/job/1.12/420/artifact/build/libs/RebornCore-1.12.2-3.13.4.420-universal.jar

Can you try this build? If the server starts up let me know.

You may not be able to login to the server with this version, if that is the case I can send you a patched version to use until the pack updates again. (We just missed an update, so it could be a week).

**Comment by Taviala** [comment] 2019-02-25 19:09
Sorry that i took so long, i managed to upload the file into the wrong modpack twice in a row >.< The server started without a problem. About the Login on the Server: that worked without a problem for me. Thanks a lot for taking the time to work on a fix .

**Comment by modmuss50** [comment] 2019-02-25 19:10
Great!

Thanks a lot for reporting it, it was an interesting bug to look into.

Have fun :)

**Closed as completed by modmuss50** 2019-02-25 19:10 UTC
Labels: bug
