### ISSUE TITLE
Blast furnace needs blast furnace to create

### ISSUE THREAD

**Issue by joncooke** [TechReborn/TechReborn#3109] opened 2023-02-05 14:11 UTC
TR: 5.4.0
MC: 1.19.2

From looking at the recipes (in-game) it seem that in order to make a blast furnace you need to already have a blast furnace.

Here's a stripped down version of the build chain dependencies.
_Cupronickel Heating Coil -> Blast Furnace_
_Nickel Ingot -> Cupronickel Heating Coil_
_Nickel Dust -> Nickel Ingot_
**Nickel Dust needs Industrial Grinder to make**
_Diamond Grinding Head -> Industrial Grinder_
_Steel Ingot -> Diamond Grinding Head_
**Steel Ingot needs Blast Furnace to make**

So it seems to be a loop.
The only other way is to rely on the recycler randomly spitting out steel nugget, but is that really the case?

I am running with REI and RER, so maybe this is actually a problem with the recipes not being displayed correctly.

**Comment by Ayutac** [comment] 2023-02-05 14:25
Duplicate of #2078

**Closed as not planned** 2023-02-05 14:25 UTC
Labels: bug, duplicate

**Comment by joncooke** [comment] 2023-02-05 15:09
The #2078 solution isn't entirely valid any more, though the route is somewhat similar.

Copper Ore in an Industrial Centrifuge will give a Nickel Nugget, so we can get the Nickel Ingot that way.

**Comment by moshner** [comment] 2023-02-07 19:32
Raw Copper works for me in the Industrial centrifuge but copper ore and deepslate copper ore are not working.

**Comment by Ayutac** [comment] 2023-02-07 19:49
they meant raw copper. copper ore is not supposed to work
