### ISSUE TITLE
Client Crash when breaking Copper Wire

### ISSUE THREAD

**Issue by kitsushadow** [TechReborn/TechReborn#1031] opened 2017-03-28 00:38 UTC
https://paste.ee/p/LfktM

I tried to break it with a pick and crashed.

**Comment by Captainaviator** [comment] 2017-03-28 01:13
another client, same server and same wire - https://pastebin.com/tfsBK7JB

something else to note, is that I have WIT installed (WAILA alternative), and this wire is the only block that doesn't show anything.

**Comment by Prospector** [comment] 2017-04-08 03:23
dupe of #987

**Closed as completed by Prospector** 2017-04-08 03:23 UTC
