### ISSUE TITLE
Outdated structures cause DFU to process every time they are loaded

### ISSUE THREAD

**Issue by Linguardium** [TechReborn/TechReborn#3243] opened 2024-04-09 23:54 UTC
**Describe the bug**

You have outdated structure files in your mod. This causes minecraft to try to update them every time they are loaded, leading to extra memory and marginally cpu usage. Please update your structures to match the mc version you are releasing for.

This should be as easy as loading them into game and re-saving them or using a mod to load them into a StructureTemplate and writing them back out to nbt during a datagen process

**Steps to Reproduce**
N/A

**Screenshots**
N/A

**Environment (please complete the following information with the version):**
verified issue still present in https://github.com/TechReborn/TechReborn/commit/39a21f4dfa5c7931bd11af99e280a4a48cc0e953

**Logs**
N/A

**Additional context**
Looks to be all the village structures you add

**Comment by Ayutac** [comment] 2024-04-29 19:17
will be addressed in a version for 1.20.6

**Comment by modmuss50** [comment] 2024-06-24 17:31
Not a bug, we dont need premature optimistation, if it can be proven to cause a noticable impact to the load time then we can think resolving it.

**Closed as not planned by modmuss50** 2024-06-24 17:31 UTC
Labels: bug
