### ISSUE TITLE
Possible Compatibility issue with Trees Do Not Float.

### ISSUE THREAD

**Issue by Zarepheth** [TechReborn/TechReborn#2557] opened 2021-10-03 00:27 UTC
**Describe the bug**
The first time I cut a tree with a Tech Reborn chainsaw, while "Trees Do Not Float" (TDNF) is installed, the whole tree collapsed to the ground and the leaves broke as expected (just like using any other tool). On subsequent cuts, the chainsaw only broke one log at a time, and the leaves failed to break or decay at the faster speed I would expect from the mod pack and additional mods I'm using.

**Steps to Reproduce**
- Create a Tech Reborn basic chainsaw - this may require some play time, use of cheats, or creative mode.
- Chop a tree with the chainsaw. First tree should break as expected with the Trees Do Not Float settings, and the chainsaw's energy will deplete as expected for durability from the TDNF settings.
- Chop a second tree with the chainsaw. Instead of breaking as expected, only one log at a time is broken. And when all logs are broken, the leaves fail to rapidly decay, instead decaying at what appears to be the Minecraft default rate, regardless of settings from other mods.

**Screenshots**
No screenshots (yet)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17.1
 - Mod Loader: Fabric
 - Valhelsia Fabric modpack (1.0.6), with some manual mod additions, updates, and disabling
   - Fabric Tree Chopper was turned off to prevent conflict with TDNF
 - Trees do not float 2.1.144 (additional mod, not part of mod pack)
 - Tech Reborn 5.0.8-beta Build 111

**Logs**
No pastebin or gist as both services failed when pasting the overly large `logs/latest.log` file into them.

**Additional context**
Because of the size of the Valhelsia Fabric modpack and the additional mods I've added, it is quite possible that the problem only appears due to the presence of additional mods, beyond the two I believe are conflicting with each other.

Cross posted on the other mod's issues:
https://github.com/grondag/trees-dont-float/issues/28

**Comment by grondag** [comment] 2021-12-22 17:09
Unable to reproduce with TDNF V3 and TR V5.0.11-beta

**Comment by modmuss50** [comment] 2021-12-22 17:11
Thanks Grondag for testing, closed this issue. If its still an issue please create a new issue. 👍

**Closed as completed** 2021-12-22 17:11 UTC
Labels: bug, mod compat
