### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by DanShu15** [TechReborn/TechReborn#2126] opened 2020-06-01 19:16 UTC
When one of our server members is online we get server errors resulting in a crash and automatic restart.

I'm not exactly sure how to reproduce it, I believe he has had his stuff set up for days, I only think it's Tech Reborn because of the log

Minecraft 1.15.2
Fabric last downloaded 5/31/2020

https://pastebin.com/2HvmGPvR

Not sure what changed, but today the server worked great until that player logged in, then his client wouldn't load his inventory or surroundings, so I had to clear his player.dat - after that the server locks up every few minutes and does an automatic restart

**Comment by DanShu15** [comment] 2020-06-01 21:29
whoa, so when I go into creative and fly to his area the server crashes and the chunks don't load. Looks like the world file is scuffed

**Comment by modmuss50** [comment] 2020-06-01 21:35
Duplicate of: https://github.com/TechReborn/TechReborn/issues/2109

It seems to be an incompatiblity with the "chainmail" library, im not sure on a good way to fix it just yet.

**Closed as completed by modmuss50** 2020-06-01 21:35 UTC
Labels: bug

**Comment by DanShu15** [comment] 2020-06-02 01:08
Sorry I don't know what that means. Is there a workaround or something I can avoid doing to prevent it happening again?

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by alexcraig** [comment] 2020-06-02 01:31
Expanded Storage is the mod that's loading the chainmail library, if you remove that from your server it should stop crashing.
