### ISSUE TITLE
Creative Solar Panel on a IC MFSU Caused a Random?? Crash.

### ISSUE THREAD

**Issue by StoneLegion** [TechReborn/TechReborn#1651] opened 2019-01-04 03:39 UTC
Hello. I wanted to test out to see if TR to IC worked and as far as I know it does. Both my friend and I are making a small pack and his game did not crash but mine did so I assume it's a bit rare.

Crash Error:
https://paste.dimdev.org/rekocixobo.mccrash

All I did was place down a MFSU then a Creative Solar Panel and bye bye game.

**Comment by StoneLegion** [comment] 2019-01-04 03:45
Odd it happen again >> I wonder what is happening my friend does not have it yet I keep getting it lol:
https://paste.dimdev.org/duqiduwibu.mccrash

This was the first Tier solar panel.

**Comment by modmuss50** [comment] 2019-01-04 10:56
odd, seems like TR-MP need updating on our side. Im out all day but will look into fixing later

**Comment by StoneLegion** [comment] 2019-01-04 15:19
Thanks mate. Yeah my tittle is derpy was not till after I realized we had diff versions and it was a 100% bug with even TR machines, etc :)

**Comment by coderbot16** [comment] 2019-01-04 21:35
@modmuss50 This looks like it was caused by my patches, since I introduced the side parameter. I think the issue is that I updated TR-MC after I sent the update to TR, so TechReborn might be pulling the old version of TR-MC?

I think that might be the case since if you take a look at the [relevant lines on github](https://github.com/TechReborn/TechReborn-ModCompatibility/blob/1.12.2/src/main/java/techreborn/compatmod/ic2/RebronCoreIC2.java#L39) it clearly implements the `ExternalPowerManager#isPoweredTile(TileEntity, EnumFacing)` function, yet the error is stating that it does not implement that function. Which would only be possible if the version on Github is out of sync with the version shipped in TechReborn.

**Comment by modmuss50** [comment] 2019-01-04 21:36
Just looked into it, it failed to build. due to a maven being down at the time.

TR always pulls the latest version, so a rebuild + new release will fix it. I will do that now, and check before releasing.

**Comment by coderbot16** [comment] 2019-01-04 21:38
Yeah, seems like one of those one-off weird errors. I was about to decompile the released JAR to be 100% sure but it looks like we already have full confirmation of the issue.

**Comment by modmuss50** [comment] 2019-01-04 21:49
Fixed in 1.12.2-2.20.1.889

**Closed as completed by modmuss50** 2019-01-04 21:49 UTC
Labels: bug, critical

**Comment by StoneLegion** [comment] 2019-01-04 21:58
Thanks all :)
