### ISSUE TITLE
(Biome O Plenty compatibility) BoP ruby dropping red garnet

### ISSUE THREAD

**Issue by 0Navis0** [TechReborn/TechReborn#595] opened 2016-05-22 18:44 UTC
I post this issue because since the compatibility between BoP and Techreborn ores has been retablished, there is still a problem with the red garnet wich isn't dropped by the BoP ruby. Would it be possible to solve this issue ?

**Comment by modmuss50** [comment] 2016-05-25 15:53
not 100% sure what the issue is?

**Comment by 0Navis0** [comment] 2016-05-25 19:09
When you break the ruby of BiomeOPlenty, it would be nice that it drops red garnet sometimes like the TechReborn ruby when the two are installed. Because if I use the BiomeOPlenty ores while the TechReborn ones (ruby, sapphire and peridot), I can't get more red garnet. Is it clearer ?

**Comment by modmuss50** [comment] 2016-05-25 19:10
yeah, that should be possible

**Comment by Prospector** [comment] 2016-05-25 22:03
Heh I said no TR sruff, but thr best way to make this work with all ores might be to use a block break event and see if the block is an oreRuby

**Comment by modmuss50** [comment] 2016-06-04 10:34
Not happening, sorry

**Comment by 0Navis0** [comment] 2016-06-04 18:37
In this case why not moving the dropping of the red garnet to another ore, like the cinnabar, it would be simpler and solve the problem.

**Comment by Prospector** [comment] 2016-06-04 20:15
I'm going to add the universal ruby drops

**Comment by Prospector** [comment] 2016-06-04 20:16
Though I would recommend disabling one of the ruby ores so you don't have two in your world.

**Comment by 0Navis0** [comment] 2016-06-04 20:57
I know it, don't worry. ;)

**Comment by 0Navis0** [comment] 2016-09-20 19:54
It has been solved ?

**Comment by modmuss50** [comment] 2016-09-20 19:54
No, wont be fixed

**Comment by 0Navis0** [comment] 2016-09-20 19:55
So why not doing what I had proposed ? Move the dropping of the red garnet to another ore, like the cinnabar, it would be simpler and solve the problem.

**Comment by 0Navis0** [comment] 2016-09-20 20:17
Do you think you could do that ? because this issue is pretty annoying.

**Comment by Prospector** [comment] 2016-09-21 06:43
I plan on doing a livestream on Saturday to work on some stuff. I could fix this one then, I bet. I would probably just fix it with a block break event, check if it's an oreRuby, and if so, then add the red garnet drops there.

**Comment by 0Navis0** [comment] 2016-09-27 18:54
Oh what is your livestream chanel ? I don't know it at all, and sorry if I missed the live. ^^'

**Comment by modmuss50** [comment] 2016-09-27 18:54
I dont think he did

**Comment by 0Navis0** [comment] 2016-09-27 18:55
Yeah but maybe he will do it soon. ;)

**Comment by Prospector** [comment] 2016-09-29 03:03
Yeah I plan on doing one this Saturday if I can. I also was thinking of starting a new mod, so I don't know.

**Comment by 0Navis0** [comment] 2016-09-29 18:52
I don't know if I will be here Saturday, I will move to my new house, it depends of the hour you do it, but Sunday I will be free. :)
Oh I enable me to come back with that, but do you think you could implement rubber slabs, stairs, fences and fence gates, because they really miss to TechReborn, even if they don't bring any tech stuff, it still brings nice deco stuff. ;)

**Closed as completed** 2016-10-18 18:40 UTC
Labels: enhancement, mod compat

**Comment by Prospector** [comment] 2016-10-18 22:19
Might be a wise idea to keep issues open that are fixed in v2 until v2 is released. Don't want people to keep reporting them, because they're not yet fixed in the publicly available version

**Comment by modmuss50** [comment] 2016-10-18 22:20
no, ive been closing issues, it stops them being fixed twice

**Comment by Prospector** [comment] 2016-10-18 22:22
Isn't that what the fixed in dev label is for?
