### ISSUE TITLE
[1.11] TechReborn 2.0.6.71 / Forge version 2188 - gem redGarnet could not be found

### ISSUE THREAD

**Issue by shortybsd** [TechReborn/TechReborn#850] opened 2016-12-17 16:57 UTC
When mining in the world or use TNT above and below ground this crash occurs. You can just run around exploring and the server will crash with this error without breaking any block.

java.security.InvalidParameterException: The gem redGarnet could not be found.
	at techreborn.items.ItemGems.getGemByName(ItemGems.java:28)
	at techreborn.items.ItemGems.getGemByName(ItemGems.java:32)
	at techreborn.blocks.BlockOre.getDrops(BlockOre.java:92)
	at techreborn.blocks.BlockOre.getDrops(BlockOre.java:36)
	at net.minecraft.block.Block.func_180653_a(Block.java:557)
	at net.minecraft.world.Explosion.func_77279_a(Explosion.java:231)
	at net.minecraft.world.WorldServer.func_72885_a(WorldServer.java:1178)
	at net.minecraft.world.World.func_72876_a(World.java:2282)
	at net.minecraft.entity.item.EntityTNTPrimed.func_70515_d(SourceFile:98)
	at net.minecraft.entity.item.EntityTNTPrimed.func_70071_h_(SourceFile:88)
	at net.minecraft.world.World.func_72866_a(World.java:1987)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1957)
	at net.minecraft.world.World.func_72939_s(World.java:1773)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at techreborn.items.ItemGems.getGemByName(ItemGems.java:28)
	at techreborn.items.ItemGems.getGemByName(ItemGems.java:32)
	at techreborn.blocks.BlockOre.getDrops(BlockOre.java:92)
	at techreborn.blocks.BlockOre.getDrops(BlockOre.java:36)
	at net.minecraft.block.Block.func_180653_a(Block.java:557)
	at net.minecraft.world.Explosion.func_77279_a(Explosion.java:231)
	at net.minecraft.world.WorldServer.func_72885_a(WorldServer.java:1178)
	at net.minecraft.world.World.func_72876_a(World.java:2282)
	at net.minecraft.entity.item.EntityTNTPrimed.func_70515_d(SourceFile:98)
	at net.minecraft.entity.item.EntityTNTPrimed.func_70071_h_(SourceFile:88)
	at net.minecraft.world.World.func_72866_a(World.java:1987)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1957)

-- Entity being ticked --
Details:
	Entity Type: minecraft:tnt (net.minecraft.entity.item.EntityTNTPrimed)
	Entity ID: 3241
	Entity Name: Block of TNT
	Entity's Exact location: 58.88, 63.07, 241.83
	Entity's Block location: World: (58,63,241), Chunk: (at 10,3,1 in 3,15; contains blocks 48,0,240 to 63,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 1.31, -0.50, 0.92
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1773)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)

**Comment by modmuss50** [comment] 2016-12-17 16:58
Dupe of: https://github.com/TechReborn/TechReborn/issues/836
Update, its been fixed.

**Closed as completed by modmuss50** 2016-12-17 16:58 UTC

**Comment by shortybsd** [comment] 2016-12-17 17:07
Thank you so much!
