### ISSUE TITLE
Acacia Boat is somehow oredictionaried as ingotAluminum

### ISSUE THREAD

**Issue by KageDragon** [TechReborn/TechReborn#652] opened 2016-06-22 14:52 UTC
Weird minor issue

Forge 12.17.0.1968
TechReborn 1.9.4-1.3.2.120
RebornCore 1.9.4-2.5.4.47
TConstruct 1.9.4-2.3.2
Mantle 1.9.4-0.10.2

**Comment by GirafiStudios** [comment] 2016-06-22 15:23
That is caused by Tinkers Construct, left in there as debug code. Already fixed in a recent comment :) You will have to wait to Tinkers Construct to update!

**Closed as completed** 2016-06-22 15:55 UTC
