### ISSUE TITLE
[1.18.2 DC] Randomly cannot join

### ISSUE THREAD

**Issue by itsdinkd** [TechReborn/TechReborn#2947] opened 2022-05-05 08:15 UTC
**Describe the bug**
After a standard automatic server restart, players who tried joining the server get disconnected immediately. The server hasn't been touched in about 8 hours, and had a couple restarts in between then and the time of players getting disconnected. Tried restarting the server multiple times to get this disconnect issue to stop but its persistent now. 

**Steps to Reproduce**
-Honestly not sure

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.2
 - Fabric 0.14.2

**Logs**
Client Log: https://gist.github.com/Sebas-Re/3abbd6b49982c26eedd70ada160a446f
Server Log: https://gist.github.com/itsdinkd/ff66c09c16823d2d556bec75368a28b7
REI Log (From client): https://spigot.pl/paste/?s=0fc1a95016fa45df
**Additional info**
When a player connects to the server, the console of the server displays the following; 
```java
[08:09:22] [Netty Epoll Server IO #1/ERROR]: Error receiving packet 102
reborncore.common.crafting.serde.RecipeSerdeException: Failed to ser/de techreborn:rolling_machine/nichrome_heating_coil
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3) ~[?:?]
	at reborncore.common.crafting.RebornRecipeType.toJson(RebornRecipeType.java:65) ~[RebornCore-5.2.0-beta.3.jar:?]
	at reborncore.common.crafting.RebornRecipeType.write(RebornRecipeType.java:79) ~[RebornCore-5.2.0-beta.3.jar:?]
	at reborncore.common.crafting.RebornRecipeType.write(RebornRecipeType.java:40) ~[RebornCore-5.2.0-beta.3.jar:?]
	at net.minecraft.network.packet.s2c.play.SynchronizeRecipesS2CPacket.writeRecipe(SynchronizeRecipesS2CPacket:52) ~[?:?]
	at net.minecraft.network.PacketByteBuf.writeCollection(PacketByteBuf:131) ~[?:?]
	at net.minecraft.network.packet.s2c.play.SynchronizeRecipesS2CPacket.write(SynchronizeRecipesS2CPacket:27) ~[?:?]
	at xyz.nucleoid.packettweaker.PacketContext.writeWithContext(PacketContext.java:29) ~[packet_tweaker-0.2.0+1.18-pre1-d9af428150ab2387.jar:?]
	at net.minecraft.network.PacketEncoder.redirect$gpf000$writePacket(PacketEncoder:1033) ~[?:?]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder:45) ~[?:?]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder:14) ~[?:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071) [netty-all-4.1.68.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-all-4.1.68.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) [netty-all-4.1.68.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalStateException: No items in c:chromium_ingots tag
	at reborncore.common.crafting.ShapedRecipeHelper.rewriteForNetworkSync(ShapedRecipeHelper.java:60) ~[RebornCore-5.2.0-beta.3.jar:?]
	at techreborn.api.recipe.recipes.serde.RollingMachineRecipeSerde.collectJsonData(RollingMachineRecipeSerde.java:29) ~[TechReborn-5.2.0-beta.3.jar:?]
	at techreborn.api.recipe.recipes.serde.RollingMachineRecipeSerde.collectJsonData(RollingMachineRecipeSerde.java:19) ~[TechReborn-5.2.0-beta.3.jar:?]
	at reborncore.common.crafting.serde.RebornRecipeSerde.toJson(RebornRecipeSerde.java:60) ~[RebornCore-5.2.0-beta.3.jar:?]
	at reborncore.common.crafting.RebornRecipeType.toJson(RebornRecipeType.java:63) ~[RebornCore-5.2.0-beta.3.jar:?]
	... 19 more
[08:09:22] [Netty Epoll Server IO #1/INFO]: [STDOUT]: REI: Server failed to synchronize recipe data with the client! Please check the server console log for errors, this breaks REI and vanilla recipe books!
```

**Comment by Ayutac** [comment] 2022-05-05 08:25
looks like the modpack did something bad to the recipe

**Comment by itsdinkd** [comment] 2022-05-05 08:46
Figured it out. It was due to running a carpet-fixes command, tagKeyMemoryLeakFix

this " Fixes a memory leak within the new TagKey system (https://bugs.mojang.com/browse/MC-248621)"

After turning off the server, and setting this command to false, the issue disappeared.

**Comment by FxMorin** [comment] 2022-05-05 15:46
Alright this is an issue for your mod. That rule in carpet-fixes is the exact way that gegy changed it in the 1.19 snapshots, so if it crashes with that rule, expect the same crash in all 1.19 builds

**Comment by Ayutac** [comment] 2022-05-05 15:55
uhm, there is no 1.19 snapshot build of TR. You know that, right?

**Comment by FxMorin** [comment] 2022-05-05 16:40
I never said there was. I said that you will need to fix this bug either way. Since it's part of 1.19

**Comment by modmuss50** [comment] 2022-05-05 16:49
This will be quite an ovious issue when I port to 1.19, but for now this works as intended on 1.18.2 the only version we provide support for. This issue is about it beign incompaible with carpet-fixes. The only documentation I can find about this in carpet is "Fixes a memory leak within the new TagKey system" this does not help me understand what its doing to cause this crash.

I do not have the time to provide support for these kinds of mods when it works fine without them. I would accpet a well tested PR if you want to fix it yourself.

For now this is something I wont be fixing.

**Closed as completed by modmuss50** 2022-05-05 16:49 UTC
Labels: bug, mod compat, wontfix

**Comment by FxMorin** [comment] 2022-05-05 18:10
Well for now just run `/carpet-fixes tagKeyMemoryLeakFix false` or set it to false in the config
I'll disable the mixin if TechReborn is running ;)
