### ISSUE TITLE
[1.12] Wrenches don't work

### ISSUE THREAD

**Issue by TheLimePixel** [TechReborn/TechReborn#1266] opened 2017-09-07 12:57 UTC
On the latest version of Reborn Core, Wrenches don't work on machines. I'm reporting it here, as the Wrench is from TR.

**Comment by drcrazy** [comment] 2017-09-07 23:42
Looks like this is already fixed in latest dev builds. I can confirm that issue reproducible in latest version from curse:
RebornCore-1.12.1-3.3.0.99-universal
TechReborn-1.12.1-2.7.0.205-universal

Please, wait till dev build will be released to curse.

![image](https://user-images.githubusercontent.com/1382352/30189818-0e2ef228-943f-11e7-9709-192bc776bbe8.png)

**Closed as completed by drcrazy** 2017-09-07 23:42 UTC

**Comment by modmuss50** [comment] 2017-09-08 07:36
Yep, I broke it, and then I fixed it a few days later.
