### ISSUE TITLE
No ore generation

### ISSUE THREAD

**Issue by Ananka59** [TechReborn/TechReborn#796] opened 2016-11-07 21:07 UTC
Hi!

I dont have ore generation from Techreborn, someone know why?

No error message in logs
Mod is charged by forge

I use :
Minecraft 1.7.10
Forge 1.10.2-12.18.2.2122
Techreborn-1.10.2-1.4.10.95
RebornCore-1.10.2-2.8.1.64

just ONLY this mod.

Thanks !!

**Comment by modmuss50** [comment] 2016-11-07 22:34
Dupe of: https://github.com/TechReborn/TechReborn/issues/794

**Closed as completed by modmuss50** 2016-11-07 22:34 UTC
