### ISSUE TITLE
[1.9] Rubber leaves render as fast

### ISSUE THREAD

**Issue by Yulife** [TechReborn/TechReborn#535] opened 2016-04-23 11:00 UTC
Should use fancy as default, fast would be an option for people with not a fast PC.

**Comment by modmuss50** [comment] 2016-04-23 11:05
Dupe of #494

**Closed as completed by modmuss50** 2016-04-23 11:05 UTC

**Comment by modmuss50** [comment] 2016-04-23 12:14
Fixed in https://github.com/TechReborn/TechReborn/commit/e7f9c679dfc0f717d03c0a44596507405a28208b
