### ISSUE TITLE
Broken recipes wich causes minecraft to crash when Inventory Tweaks is installed or when I go in the control parameters durring the game

### ISSUE THREAD

**Issue by 0Navis0** [TechReborn/TechReborn#553] opened 2016-05-06 15:11 UTC
Ok I post this crash here too because I think that TechReborn has a link with this crash. I get a serious crash when I try to launch minecraft with the last 1.9 version of Inventory Tweaks, TechReborn and Quark.
http://pastebin.com/U3mHZgSa

I noticed that when I create a new word, I get these errors. It doesn't make the game to crash, but I think it's the reason of why Inventory Tweaks crashes when it's installed. It seems that Quark and TechReborn add broken recipes.
http://pastebin.com/6bLwa8ga

In final I get a crash when I go in the command control when I'm playing into a word, but not when I'm in the menu, and I think that it's linked to the same problem.
http://pastebin.com/FALUi14a

I think that all these errors are linked. I informed the owners of Quark and Inventory Tweaks too. You should take contacts with them. I created an issue in the Quark github too.
Vazkii/Quark#28

**Comment by modmuss50** [comment] 2016-05-06 15:24
Can someone point me to the inv tweeks dev?

**Comment by 0Navis0** [comment] 2016-05-06 15:33
I can't find it on Github, but here is the CurseForge page. http://minecraft.curseforge.com/projects/inventory-tweaks

**Comment by vegeta897** [comment] 2016-05-06 15:35
I believe this is the relevant issue: Inventory-Tweaks/Inventory-Tweaks#342

**Comment by 0Navis0** [comment] 2016-05-06 15:40
Yeah this crash has been reported many times to the Inventory Tweaks owner. But it seems that nobody had made the link with the broken recipes of TechReborn and Quark.

**Comment by modmuss50** [comment] 2016-05-06 16:44
If you read what he has said in the issue, its not an issue with TechReborn and he is waiting for the next version of modded minecraft. Dupe of #545 and #531 .

**Closed as completed by modmuss50** 2016-05-06 16:44 UTC

**Comment by modmuss50** [comment] 2016-05-07 08:21
Turns out there is a PR to fix this: https://github.com/Inventory-Tweaks/inventory-tweaks/pull/347
