### ISSUE TITLE
[1.14.4] Fabric - Error connecting to Server

### ISSUE THREAD

**Issue by Atomkraftzwerg1** [TechReborn/TechReborn#1877] opened 2019-10-28 10:58 UTC
Hi,
i added TechReborn "TechReborn-1.14.4-3.0.18+build.256.jar'" on my Server.
when i try to connect, i get 

"Internal Exception: io.netty.handler.codec.EncoderException: Java.lang.NullPointerException"

I really hope you can help me, i added the logfile.

PS: if u have any questions, let me know.

[latest.log](https://github.com/TechReborn/TechReborn/files/3778336/latest.log)

**Comment by modmuss50** [comment] 2019-10-28 15:11
Duplicate of #1876 

Should be fixed in RebornCore 4.0.21, let me know if you still have issues with that.

**Closed as completed by modmuss50** 2019-10-28 15:11 UTC

**Comment by Atomkraftzwerg1** [comment] 2019-10-28 23:14
I installed the newer version "TechReborn-1.14.4-3.0.18+build.256.jar" and it works.

Thanks :-)
