### ISSUE TITLE
Console is being spammed when another mod changes "mayfly" property

### ISSUE THREAD

**Issue by burdoto** [TechReborn/TechReborn#3261] opened 2024-06-24 14:48 UTC
**Describe the bug**
Console is being spammed when another mod changes "mayfly" property

**Steps to Reproduce**
- Install TechReborn and e.g. [EssentialsCommands](https://modrinth.com/mod/essentials-commands)
- Use `/fly` from EssentialsCommands
- Console is being spammed every tick

**Screenshots**
![image](https://github.com/TechReborn/TechReborn/assets/42473485/0c360866-6250-442f-a493-46d47b007223)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.20.1
 - Mod Loader: Fabric

**Logs**
https://paste.kescher.at/?4cb456a237593add#E47M8mfQChL9ycVtPg7etBvn3sxqR1mS6CgdwEHG6QHP

**Comment by modmuss50** [comment] 2024-06-24 17:08
Duplicate of: https://github.com/TechReborn/TechReborn/issues/3186

**Closed as not planned by modmuss50** 2024-06-24 17:08 UTC
Labels: bug
