### ISSUE TITLE
The problem with the cables if world reloading and extreme energy consumptio (1.11.2) - all mods are update on last version - video

### ISSUE THREAD

**Issue by Umiyaki** [TechReborn/TechReborn#958] opened 2017-02-02 07:21 UTC
Minecraft 1.11.2
Forge 13.20.0.2226
TechReborn-1.11.2-2.1.3.54-universal.jar
RebornCore-1.11.2-2.13.3.34-universal.jar

video 1:50min
https://youtu.be/HOdAvXzTx3A

**Comment by Barhandar** [comment] 2017-02-04 09:18
Not world unloading, machine unloading. Happens in 1.10.2 too.

I have a watermill - two copper cables - grinder setup and grinder stops being powered every time that chunk is unloaded (which obviously happens on world unload, but also if I move too far or switch dimension).

Dupe of #926 btw.

**Closed as completed** 2017-05-18 18:39 UTC
Labels: bug
