### ISSUE TITLE
Crashing with InvTweaks

### ISSUE THREAD

**Issue by MCEventHorizon** [TechReborn/TechReborn#545] opened 2016-04-29 22:06 UTC
I think it's an issue with TechReborn since InvTweaks works without it:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-beta-18.jar)
  NowWithRendering (redstonepaste-mc1.9-1.7.3.jar)
  FldLoadingPlugin (FastLeafDecay-1.9-1.6.jar)
  LoadingPlugin (RandomThings-MC1.9-3.7.jar)
  FMLPlugin (InventoryTweaks-1.61-dev-45.jar)
  Reborn Core ASM (RebornCore-1.9-2.1.0.53-universal.jar)
  LoadingPlugin (ResourceLoader-MC1.9-1.5.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 4/30/16 12:04 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.IllegalAccessError: tried to access field net.minecraftforge.oredict.OreDictionary$OreRegisterEvent.Name from class invtweaks.InvTweaksItemTree
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:179)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:739)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:307)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:513)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:346)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalAccessError: tried to access field net.minecraftforge.oredict.OreDictionary$OreRegisterEvent.Name from class invtweaks.InvTweaksItemTree
    at invtweaks.InvTweaksItemTree.lambda$oreRegistered$5(InvTweaksItemTree.java:288)
    at invtweaks.InvTweaksItemTree$$Lambda$165/625380424.test(Unknown Source)
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
    at invtweaks.InvTweaksItemTree.oreRegistered(InvTweaksItemTree.java:288)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_403_InvTweaksItemTree_oreRegistered_OreRegisterEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:522)
    at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:469)
    at techreborn.init.ModBlocks.registerOreDict(ModBlocks.java:482)
    at techreborn.init.ModBlocks.init(ModBlocks.java:476)
    at techreborn.Core.init(Core.java:105)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:737)
    ... 10 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.9
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 439280752 bytes (418 MB) / 1358204928 bytes (1295 MB) up to 4187619328 bytes (3993 MB)
    JVM Flags: 13 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4472m -Xms256m -XX:PermSize=256m -Xmn1G -Xmx4G -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:MaxGCPauseMillis=80 -XX:+UseStringDeduplication -XX:+UseCompressedOops -XX:+UseCodeCacheFlushing -XX:ParallelGCThreads=4
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.23 Powered by Forge 12.16.0.1867 76 mods loaded, 76 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHI    mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHI    FML{8.0.99.99} [Forge Mod Loader](forge-1.9-12.16.0.1867-1.9.jar) 
    UCHI    Forge{12.16.0.1867} [Minecraft Forge](forge-1.9-12.16.0.1867-1.9.jar) 
    UCHI    cei{1.1.1} [Chunk Edge Indicator](1.9-chunkedgeindicator-1.1.1.jar) 
    UCHI    actuallyadditions{1.9-r28} [Actually Additions](ActuallyAdditions-1.9-r28.jar) 
    UCHI    Baubles{1.2.0.2} [Baubles](Baubles-1.9-1.2.0.2.jar) 
    UCHI    bdlib{1.11.0.14} [BD Lib](bdlib-1.11.0.14-mc1.9.jar) 
    UCHI    BetterAchievements{0.2.2} [Better Achievements](BetterAchievements-1.9-0.2.2.jar) 
    UCHI    BBG{4.0.0} [BetterBedrockGen](BetterBedrockGenerator-1.9.0-3.0.0.jar) 
    UCHI    BiomesOPlenty{4.0.2.2018} [Biomes O' Plenty](BiomesOPlenty-1.9-4.0.2.2018-universal.jar) 
    UCHI    JEI{3.2.14.190} [Just Enough Items](jei_1.9-3.2.14.190.jar) 
    UCHI    blockdrops{1.0.0} [Block Drops](Block Drops-1.9-1.0.0.jar) 
    UCHI    BloodMagic{1.9-2.0.0-34} [Blood Magic: Alchemical Wizardry](BloodMagic-1.9-2.0.0-34.jar) 
    UCHI    bookshelf{1.2.0.226} [Bookshelf](Bookshelf-1.9-1.2.0.237.jar) 
    UCHI    bookshelfapi{3.0.4} [Bookshelf](Bookshelf-API-1.9-3.0.4.jar) 
    UCHI    Botania{r1.8-302} [Botania](Botania-unofficial.r1.8-302.jar) 
    UCHI    Chameleon{1.9-2.1.3} [Chameleon](Chameleon-1.9-2.1.3.jar) 
    UCHI    chisel{@VERSION@} [Chisel](Chisel-MC1.9-0.0.4.13.jar) 
    UCHI    mcmultipart{1.1.1} [MCMultiPart](MCMultiPart-1.1.1-universal.jar) 
    UCHI    chiselsandbits{9.14} [Chisels & Bits](chiselsandbits-9.14.jar) 
    UCHI    craftingtweaks{4.0.10} [Crafting Tweaks](craftingtweaks-mc1.9-4.0.10.jar) 
    UCHI    CustomMainMenu{2.0} [Custom Main Menu](CustomMainMenu-MC1.9-2.0.jar) 
    UCHI    Waila{1.7.0} [Waila](Waila-1.7.0-B2_1.9.jar) 
    UCHI    DarkUtils{1.1.0.32} [Dark Utilities](DarkUtilities-1.9-1.1.0.33.jar) 
    UCHI    ElecCore{1.4.270} [ElecCore](ElecCore-1.9-1.4.270.jar) 
    UCHI    deepresonance{1.1.4beta30} [DeepResonance](deepresonance-1.9.0-1.1.4beta30.jar) 
    UCHI    dldungeonsjdg{1.8.11} [Doomlike Dungeons](DoomlikeDungeons-1.8.11-MC1.9.jar) 
    UCHI    enderbook{1.0.3} [Ender Book](EnderBook-1.9-1.0.3.jar) 
    UCHI    enderrift{0.15.0} [Ender-Rift](EnderRift-1.9-0.15.0.jar) 
    UCHI    enderutilities{0.5.1} [Ender Utilities](enderutilities-1.9-0.5.1.jar) 
    UCHI    ezstorage{1.0} [EZ Storage](ezstorage-1.9-1.2.1.jar) 
    UCHI    FFS{1.9-1.5.1.1.2} [Fancy Fluid Storage](Fancy Fluid Storage-1.9-1.5.1.1.2.jar) 
    UCHI    fastleafdecay{1.6} [Fast Leaf Decay](FastLeafDecay-1.9-1.6.jar) 
    UCHI    flatcoloredblocks{mc1.9-v2.2} [Flat Colored Blocks](flatcoloredblocks-mc1.9-v2.2.jar) 
    UCHI    substratum{1.3.0.0} [Substratum](Substratum-1.9-1.3.0.0.jar) 
    UCHI    foundry{2.0.0.0-alpha2} [Foundry](Foundry-1.9-2.0.0.0-alpha2.jar) 
    UCHI    advgenerators{0.9.20.7} [Advanced Generators](generators-0.9.20.7-mc1.9.jar) 
    UCHI    gravestone{1.2.4} [Gravestone](Gravestone Mod 1.2.4 .jar) 
    UCHI    inventorytweaks{1.61-dev-45-29e0ed5} [Inventory Tweaks](InventoryTweaks-1.61-dev-45.jar) 
    UCHI    IronChest{6.0.133.777} [Iron Chest](ironchest-1.9-6.0.133.777.jar) 
    UCHI    journeymap{1.9-5.2.0b1} [JourneyMap](journeymap-1.9-5.2.0b1-unlimited.jar) 
    UCHI    jeresources{0.4.3} [Just Enough Resources](JustEnoughResources-1.9-0.4.3.jar) 
    UCHI    JET{1.2.28} [JustEnoughTooltips](JustEnoughTooltips-1.9-1.2.28.jar) 
    UCHI    jwin{univ_compat_filler} [Just What I Needed](jwin-0.12.3.jar) 
    UCHI    mantle{1.9-0.9.4.jenkins114} [Mantle](Mantle-1.9-0.9.4.jar) 
    UCHI    testdummy{1.10} [MmmMmmMmmMmm](MmmMmmMmmMmm-1.10.jar) 
    UCHI    Morpheus{1.9-3.0.2} [Morpheus](Morpheus-1.9-3.0.2.jar) 
    UCHI    MouseTweaks{2.6.2} [Mouse Tweaks](MouseTweaks-2.6.2-mc1.9.jar) 
    UCHI    Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat](Neat 1.2-5.jar) 
    UCHI    tconstruct{1.9-2.2.2.jenkins156} [Tinkers' Construct](TConstruct-1.9-2.2.2.jar) 
    UCHI    neotech{3.0.6} [NeoTech](NeoTech-1.9-3.0.6.jar) 
    UCHI    netherportalfix{1.0} [Nether Portal Fix](netherportalfix-mc1.9-3.0.6.jar) 
    UCHI    notenoughwands{1.3.1} [Not Enough Wands](notenoughwands-1.9.0-1.3.1.jar) 
    UCHI    samsocean{1.0.0} [Classic Oceans](OceanFloor-1.9-1.0.1.jar) 
    UCHI    progressiveautomation{1.6.42} [Progressive Automation](ProgressiveAutomation-1.9-1.6.42.jar) 
    UCHI    Psi{beta-31} [Psi](Psi-beta-31.jar) 
    UCHI    quantumflux{2.0.4} [QuantumFlux](quantumflux-1.9-2.0.4.jar) 
    UCHI    Quark{beta-18} [Quark](Quark-beta-18.jar) 
    UCHI    randomthings{3.7} [Random Things](RandomThings-MC1.9-3.7.jar) 
    UCHI    reborncore{2.1.0.53} [RebornCore](RebornCore-1.9-2.1.0.53-universal.jar) 
    UCHI    redstonepaste{1.7.3} [Redstone Paste](redstonepaste-mc1.9-1.7.3.jar) 
    UCHI    xreliquary{1.9-1.3.1.322} [Reliquary](Reliquary-1.9-1.3.1.322.jar) 
    UCHI    ResourceLoader{1.5} [Resource Loader](ResourceLoader-MC1.9-1.5.jar) 
    UCHI    rftools{4.45} [RFTools](rftools-1.9.0-4.45.jar) 
    UCHI    rftoolsdim{4.23beta37} [RFTools Dimensions](rftoolsdim-1.9.0-4.23beta37.jar) 
    UCHI    Roguelike{1.5.0} [Roguelike Dungeons](RoguelikeDungeons-1.9-1.5.0.jar) 
    UCHI    RTG{1.9-0.0.5} [Realistic Terrain Generation](RTG-1.9-0.0.5.jar) 
    UCHI    StorageDrawers{1.9-3.1.6} [Storage Drawers](StorageDrawers-1.9-3.1.6.jar) 
    UCHE    techreborn{1.0.6.197} [TechReborn](TechReborn-1.9-1.0.6.197-universal.jar) 
    UCHI    VeinMiner{0.31.5_build.forgePost18010} [Vein Miner](VeinMiner-1.9_0.31.5.forgePost18010.jar) 
    UCHI    VeinMinerModSupport{0.31.5_build.forgePost18010} [Mod Support](VeinMiner-1.9_0.31.5.forgePost18010.jar) 
    UCHI    WailaHarvestability{1.1.7} [Waila Harvestability](WailaHarvestability-mc1.9-1.1.7.jar) 
    UCHI    ICSE{1.0.0.0} [I Can See Everything](Wawla-1.9-2.2.0.186.jar) 
    UCHI    wawla{2.2.0.178} [What Are We Looking At](Wawla-1.9-2.2.0.186.jar) 
    UCHI    YAFM{1.0.5} [Yet Another Food Mod](yafm-1.0.5-mc1.9.jar) 
    UCHI    YALSM{2.1.6} [Yet Another Leather Smelting Mod](yalsm-2.1.6-mc1.9.jar) 
    Loaded coremods (and transformers): 
LoadingPlugin (Quark-beta-18.jar)
  vazkii.quark.base.asm.ClassTransformer
NowWithRendering (redstonepaste-mc1.9-1.7.3.jar)
  net.fybertech.nwr.NowWithRendering
FldLoadingPlugin (FastLeafDecay-1.9-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
LoadingPlugin (RandomThings-MC1.9-3.7.jar)
  lumien.randomthings.asm.ClassTransformer
FMLPlugin (InventoryTweaks-1.61-dev-45.jar)
  invtweaks.forge.asm.ContainerTransformer
Reborn Core ASM (RebornCore-1.9-2.1.0.53-universal.jar)
  reborncore.asm.RebornClassTransformer
LoadingPlugin (ResourceLoader-MC1.9-1.5.jar)
  lumien.resourceloader.asm.ClassTransformer
    GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13431 Compatibility Profile Context 16.150.2211.1001' Renderer: 'AMD Radeon R7 200 Series'
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - chiselsandbitsIntegration (Enabled/Not Forced)
        - craftingtweaksIntegration (Enabled/Not Forced)

```
List of loaded APIs: 
    * actuallyadditionsapi (8) from ActuallyAdditions-1.9-r28.jar
    * Baubles|API (1.1.1.0) from Baubles-1.9-1.2.0.2.jar
    * BetterAchievements|API (0.2.2) from BetterAchievements-1.9-0.2.2.jar
    * BloodMagic|API (@VERSION@) from BloodMagic-1.9-2.0.0-34.jar
    * BotaniaAPI (78) from Botania-unofficial.r1.8-302.jar
    * CapabilityCore|base (1.01) from EnderRift-1.9-0.15.0.jar
    * CapabilityCore|energy (1.01) from EnderRift-1.9-0.15.0.jar
    * CapabilityCore|tweakable (1.01) from EnderRift-1.9-0.15.0.jar
    * ChiselAPI (0.0.1) from Chisel-MC1.9-0.0.4.13.jar
    * ChiselAPI|Carving (0.0.1) from Chisel-MC1.9-0.0.4.13.jar
    * ChiselsAndBitsAPI (1.8.1) from chiselsandbits-9.14.jar
    * CoFHAPI (1.8.9R1.2.0B1) from Fancy Fluid Storage-1.9-1.5.1.1.2.jar
    * CoFHAPI|block (1.8.9R1.2.0B1) from ProgressiveAutomation-1.9-1.6.42.jar
    * CoFHAPI|energy (1.8.9R1.2.0B1) from Foundry-1.9-2.0.0.0-alpha2.jar
    * CoFHAPI|tileentity (1.8.9R1.2.0B1) from ProgressiveAutomation-1.9-1.6.42.jar
    * CraftingTweaks|API (4.1) from craftingtweaks-mc1.9-4.0.10.jar
    * DLDungeonsAPI (1.1) from DoomlikeDungeons-1.8.11-MC1.9.jar
    * DR-API (1.0.4-Beta) from deepresonance-1.9.0-1.1.4beta30.jar
    * ElecCore|Abilities (#API_VER#) from ElecCore-1.9-1.4.270.jar
    * foundry.api (2.0.0.0) from Foundry-1.9-2.0.0.0-alpha2.jar
    * IC2API (1.0) from RebornCore-1.9-2.1.0.53-universal.jar
    * jeresources|API (0.4.3) from JustEnoughResources-1.9-0.4.3.jar
    * journeymap|client-api (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
    * journeymap|client-api-display (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
    * journeymap|client-api-event (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
    * journeymap|client-api-model (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
    * journeymap|client-api-util (1.2-SNAPSHOT) from journeymap-1.9-5.2.0b1-unlimited.jar
    * JustEnoughItemsAPI (3.1.0) from jei_1.9-3.2.14.190.jar
    * McJtyLib (1.9.0-1.8.2) from mcjtylib-1.9.0-1.8.2.jar
    * PsiAPI (2) from Psi-beta-31.jar
    * reborncoreAPI (2.1.0.53) from RebornCore-1.9-2.1.0.53-universal.jar
    * StorageDrawersAPI (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
    * StorageDrawersAPI|config (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
    * StorageDrawersAPI|event (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
    * StorageDrawersAPI|inventory (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
    * StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
    * StorageDrawersAPI|registry (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
    * StorageDrawersAPI|render (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
    * StorageDrawersAPI|storage (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
    * StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.6.jar
    * techrebornAPI (1.0.6.197) from TechReborn-1.9-1.0.6.197-universal.jar
    * VeinMinerApi (0.1) from VeinMiner-1.9_0.31.5.forgePost18010.jar
    * WailaAPI (1.3) from Waila-1.7.0-B2_1.9.jar
```

**Comment by modmuss50** [comment] 2016-04-29 22:07
Report it to them not me. Dupe of #531

**Closed as completed by modmuss50** 2016-04-29 22:07 UTC
