### ISSUE TITLE
Gem armor unbalanced in the current state.

### ISSUE THREAD

**Issue by ImAK9** [TechReborn/TechReborn#2186] opened 2020-07-30 20:38 UTC
**Is your feature request related to a problem? Please describe.**
Gem armor dosen't scale well with other mods & the fact that you can get gem armor so early on ruins progression by ALOT.

**Describe the solution you'd like**
A config option for durability & armor it gives. Could also just nerf it in general.

**Comment by ImAK9** [comment] 2020-07-30 20:39
Kinda related to #2181 aswell, not sure why he reported as a bug tho..

**Comment by drcrazy** [comment] 2020-09-01 17:50
Duplicate of #2181

**Closed as completed by drcrazy** 2020-09-01 17:50 UTC
Labels: enhancement
