### ISSUE TITLE
[1.16.5] Fusion Reactor Glitches World

### ISSUE THREAD

**Issue by AlexisBloodwood** [TechReborn/TechReborn#2382] opened 2021-04-06 17:23 UTC
**Describe the bug**
Alright so, OpenGL threw an error when putting Helium3 and Der into the Fusion Reactor which ended up hiding every entity within my world. I have to relog to be able to see everything again, and it only happens when interacting with the Fusion Reactor. 

**Steps to Reproduce**
- Create base size 6 Fusion Reactor
- Add ingredients for Heliumplasma

**Screenshots**
![2021-04-06_12 12 34](https://user-images.githubusercontent.com/69871764/113752009-213ee280-96d2-11eb-92f7-a1655e545b95.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.5
 - Mod Loader: Fabric

**Logs**
0bin refuses to encrypt my Log, as its almost 8k KB: 
[latest.log](https://github.com/TechReborn/TechReborn/files/6266466/latest.log)

**Additional context**
I have a sneaking suspicion its Optifabric causing this and that haunts me. Luckily I've found other ways of power though I want to try and find a solution to this so other people don't have to deal with this problem.

**Comment by jusvit** [comment] 2021-09-20 10:05
Can't reproduce nor has anyone mentioned this issue, I suspect it had something to do with Optifabric. 

Closing for now...

**Closed as completed by jusvit** 2021-09-20 10:05 UTC
Labels: bug
