### ISSUE TITLE
No Recipes in 1.8.9

### ISSUE THREAD

**Issue by xKillerbees** [TechReborn/TechReborn#330] opened 2016-01-21 09:57 UTC
Pretty sure you are aware, just didn't see an issue for it to make it 'official'.

**Comment by modmuss50** [comment] 2016-01-21 11:07
The thing is this mod is an IC2 addon, and recipes use IC2. So when there is no IC2 there is no recipes. This does happen when you run the 1.7 version without IC2. It may be fixed, or you might just have to wait for ic2 to update.

**Comment by modmuss50** [comment] 2016-01-21 11:08
Dupe of #157 #182 #310

**Comment by modmuss50** [comment] 2016-02-20 01:12
see #339

**Closed by modmuss50** 2016-02-20 01:12 UTC
Labels: bug, Recipe, standalone
