### ISSUE TITLE
[1.11.2] Power system completely buggy

### ISSUE THREAD

**Issue by Skillotic0703** [TechReborn/TechReborn#1088] opened 2017-05-22 16:22 UTC
I'm using forge 13.20.0.2299 TechReborn 2.3.0.152 and RebornCore 2.16.0.106. Nothing is working as intended: 
1) You can power any machine with any tier of generator.
2) You can't power machines with cables, you need to have the machine adjacent to the generator or battery but you can power other batteries with cables so you can put copper cables between two battery boxes and power will transfer.
3) A battery can't input and output energy at the same time

**Comment by Tyler799** [comment] 2017-05-23 21:31
Also experiencing this on the latest builds for 1.11.2. What a bummer, I'd love to get to play. Haven't been able to play this save for like, a month or more now because of TR being broken. Don't feel like messing with it until it's fully fixed.

**Comment by TheLimePixel** [comment] 2017-05-24 12:31
Yeah, this is a massive bug and must be fixed.

**Comment by drcrazy** [comment] 2017-05-24 21:21
MC 1.11.2, Forge 13.20.0.2294, Reborn Core 2.16.0.106 and Tech Reborn 2.3.0.152

Heat generator connected to grinder using insulated copper cable. Cable is not giving energy to grinder (

**Comment by modmuss50** [comment] 2017-05-25 19:40
Ok, turns out I had uncommitted changes, would you mind testing with this version to see if that is the cause of the issues? https://jenkins.modmuss50.me/job/TeamReborn/job/TechReborn/job/TechReborn-1.11.2/

**Comment by Skillotic0703** [comment] 2017-05-25 21:33
You solved all the problems except for the second one. So you need a batbox at the bottom of every machine.

**Comment by modmuss50** [comment] 2017-05-25 22:01
Ok, I will push that version as a beta as it makes it better, and look into the other issue another day.

**Comment by TheLimePixel** [comment] 2017-05-25 23:09
Would it be out by 12 p.m. EST on Sunday?

**Comment by modmuss50** [comment] 2017-05-25 23:09
I don't know, it will be done when it's done.

**Comment by modmuss50** [comment] 2017-05-26 08:25
Fixed in the next version of RebornCore

**Closed as completed** 2017-05-26 08:25 UTC
