### ISSUE TITLE
Failed to load zombie villager texture

### ISSUE THREAD

**Issue by DemonMartin** [TechReborn/TechReborn#3025] opened 2022-08-24 10:32 UTC
**Describe the bug**
Missing zombie villager texture
**Steps to Reproduce**
Just spawn a Zombie Villager with the profession electrician

**Screenshots**
[http://share.martin.tools/‌‌‍‍​‍⁠​‍​‍​](https://share.martin.tools/%E2%80%8C%E2%80%8C%E2%80%8D%E2%80%8D%E2%80%8B%E2%80%8D%E2%81%A0%E2%80%8B%E2%80%8D%E2%80%8B%E2%80%8D%E2%80%8B/direct)
**Environment (please complete the following information with the version):**
 - 1.18.2
 - Fabric 0.14.9

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
https://bin.dojnaz.cloud/uwahe.apache

**Additional context**
I'm testing it in a modpack with other mods.

**Comment by Ayutac** [comment] 2022-08-24 12:16
Duplicate of #2974

**Closed as completed by Ayutac** 2022-08-24 12:16 UTC
Labels: bug, duplicate

**Comment by DemonMartin** [comment] 2022-08-24 12:20
This mentioned fix doesn't fix my problem, tho. I have already installed the newest Tech Reborn Version for 1.18.2 (Fabric). (Version 5.,2.0)

**Comment by Ayutac** [comment] 2022-08-24 12:21
New version with the fix isn't released yet :)

**Comment by DemonMartin** [comment] 2022-08-24 12:22
Oh, okay, Sorry & Thanks 👍
