### ISSUE TITLE
Still Couldn't Find Any Iridium Ore

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#950] opened 2017-02-01 10:45 UTC
playing for 3 months, created 5 worlds and still couldn't find any iridium ore. it got annoying now..

**Comment by Ourten** [comment] 2017-02-01 11:29
Duplicate of #949

**Closed as completed by Ourten** 2017-02-01 11:29 UTC

**Comment by ghost** [comment] 2017-02-01 11:41
not duplicate... i say no iridium ore, he say no small vein ore...

**Comment by modmuss50** [comment] 2017-02-01 11:41
It is, we spent a lot of time yesterday figuring it out.
