### ISSUE TITLE
TR machines can't interact with AE2 item interfaces

### ISSUE THREAD

**Issue by urmet** [TechReborn/TechReborn#2584] opened 2021-10-27 09:50 UTC
**Describe the bug**
TR machines(for example a grinder) can't pull items from the interface for processing and can't push resulting items out into the interface either. 

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17
 - Mod Loader: fabric
 - TR build 131
 - AE2 alpha.7

**Comment by Technici4n** [comment] 2021-10-28 14:44
Duplicate of #2574

**Closed as completed by Technici4n** 2021-10-28 14:44 UTC
Labels: bug
