### ISSUE TITLE
Some items lack textures/models, showing the missing texture icon.

### ISSUE THREAD

**Issue by mystise** [TechReborn/TechReborn#430] opened 2016-03-27 18:42 UTC
![2016-03-27_12 29 57](https://cloud.githubusercontent.com/assets/246232/14067081/3929470c-f419-11e5-8b28-cd4200cb77c2.png)
![2016-03-27_12 37 03](https://cloud.githubusercontent.com/assets/246232/14067083/393882e4-f419-11e5-97c6-3eddecccc6b0.png)
![2016-03-27_12 39 12](https://cloud.githubusercontent.com/assets/246232/14067082/3937ebcc-f419-11e5-9590-50f770b3b90c.png)

The diamond jackhammer and the teleporter also show the missing texture icon, but they aren't craftable yet.

**Comment by modmuss50** [comment] 2016-03-27 18:43
Dupe of #400

**Closed as completed by modmuss50** 2016-03-27 18:43 UTC
