### ISSUE TITLE
Machine Texture Animation Issues.

### ISSUE THREAD

**Issue by StoneLegion** [TechReborn/TechReborn#1661] opened 2019-01-31 22:10 UTC
This is a bit of a strange one. At first I thought there was no Animated textures for TR machines. But I found out it was due to the orientation it was facing.

Simple setup via MP was that my Industrial Blast Furnace and Industrial Grinder facing North has no Animations. But on the other side the ones facing South was working just fine.  

I took longer to test placing this on North South East and West and all of them work fine but the North side

**Comment by modmuss50** [comment] 2019-01-31 22:51
Do you have any performance mods? such as VanillaFix, FoamFix, or Optifine? As they all make tweaks to the animated texture system.

If so could you try removing these to see if that helps?

**Comment by StoneLegion** [comment] 2019-01-31 23:23
I did try removing FoamFix / VanillaFix / BetterFPS without any changes. I don't use Optifine right now. I don't think I have other tweak mods that should effect animated textures / textures.

I will play around with it more and make a instance later without anything else.

**Comment by modmuss50** [comment] 2019-02-01 13:50
Cannot reproduce

**Comment by modmuss50** [comment] 2019-02-14 15:29
Closing as no one else has this issue, and I have nothing more to go off.

**Closed as completed by modmuss50** 2019-02-14 15:29 UTC
Labels: unverified
