### ISSUE TITLE
Server Crash - Mek windmilll charging a chainsaw.

### ISSUE THREAD

**Issue by ProsperCraft** [TechReborn/TechReborn#754] opened 2016-09-23 01:23 UTC
https://github.com/aidancbrady/Mekanism/issues/3825

Different api versions or something?

**Comment by modmuss50** [comment] 2016-09-23 06:52
Fix for now is to disable forge and RF power in the reborn core config, log back in, remove items, and then enable it again.

and dupe of: https://github.com/TechReborn/TechReborn/issues/696

**Closed as completed by modmuss50** 2016-09-23 06:52 UTC

**Comment by ProsperCraft** [comment] 2016-09-24 02:42
The reborn core config does not have the option to disable forge and RF power that I can find anywhere.
