### ISSUE TITLE
TR machines don't accept / provide power in EU-only mode

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [TechReborn/TechReborn#1710] opened 2019-04-16 20:15 UTC
Hey there,

I wanted to try setting TechReborn / RebornCore to EU-only mode in my pack for balance reasons (using RebornCore's power.cfg), but this seems to just have broken the mod's power transfer entirely - the Generator for instance just won't transfer its power to other machines anymore.

In fact, the machine appear to not even want to connect to their own mod's cables anymore (see image)
![image](https://user-images.githubusercontent.com/12750501/56240911-d961c380-6094-11e9-9946-f66fc416cd65.png)

I don't have IC² in the pack at all, however I figured making TechReborn the go-to early game EU mod might be an okay idea to balance out the progression.

I hope you're able to reproduce this issue as well - as I said, there's nothing that should really be off here except for maybe the missing Industrial Craft, that **might** have *something* to do with it

**Comment by modmuss50** [comment] 2019-04-16 21:09
duplicate of #1705

**Closed as completed by modmuss50** 2019-04-16 21:09 UTC

**Comment by coderbot16** [comment] 2019-04-16 21:45
EU only mode requires IC2 to be installed, otherwise there will be no available power systems. This is only a partial duplicate - perhaps we should stop users from disabling RF if they don’t have a mod supporting EU.
