### ISSUE TITLE
TechReborn cables do not connect to blocks from other mods

### ISSUE THREAD

**Issue by ArcusMG** [TechReborn/TechReborn#902] opened 2017-01-16 03:38 UTC
I'm running Minecraft 1.11.2. 

I have TechReborn 1.11.2-2.1.0.32 installed

Other mods seem to be able to send power into TechReborn energy storage and some TechReborn machines using their own cables/power transfer but no TechReborn cables will connect to blocks from other mods. Also once power is in a TechReborn block, it can't be transferred to any other mod's blocks, even using cables from that other mod.

http://i.imgur.com/Zc7xdkw.png
http://i.imgur.com/O7oSSsx.png
http://i.imgur.com/MbJ6Pps.png
http://i.imgur.com/Hp5JlkN.png

**Comment by modmuss50** [comment] 2017-01-16 09:16
This is intended behavior, but I wont close it as I feel like I should redo the cables to allow this.

**Comment by ghost** [comment] 2017-01-16 10:34
im agreeing this.. it would be good to connect to forestry machines especially...

**Comment by ArcusMG** [comment] 2017-01-16 13:49
Ahh! Ok, that makes sense. At first I thought I was just doing something wrong. I look forward to the change. I know it's a back burner, future thing but thanks for taking the time to read it and let me know what's going on. :)

**Comment by modmuss50** [comment] 2017-01-17 22:14
This will come when its done. Not a lot of point having an issue here.

**Closed as completed by modmuss50** 2017-01-17 22:14 UTC
Labels: enhancement, low priority
