### ISSUE TITLE
Basic circuit board is uncraftable but used in some items

### ISSUE THREAD

**Issue by mystise** [TechReborn/TechReborn#471] opened 2016-03-29 02:44 UTC
Namely:
- Destructopack
- Rock cutter

![2016-03-28_20 06 48](https://cloud.githubusercontent.com/assets/246232/14096409/da625412-f525-11e5-9c49-6683acb11698.png)

**Comment by Prospector** [comment] 2016-03-29 02:59
Dupe of #401

**Closed as completed by Prospector** 2016-03-29 02:59 UTC
