### ISSUE TITLE
Machine recipes allow all ore dict tags of an item

### ISSUE THREAD

**Issue by EverybodyLies** [TechReborn/TechReborn#381] opened 2016-03-09 12:01 UTC
Using TechReborn-1.7.10-0.7.15.1096 i added few recipes via MineTweaker. 
`grinder.addRecipe(Dust, null, null, null, Ingot, null, 100, 32);`

Problem is: grinder recipes takes all oredict-tags from Ingot (i have 4 tags) and uses it as input conditions, that ruined all recipe logic. Here's an example:

Ingot info:

```
<TabulaRasa:RasaItem7:7> // that id (TabulaRasa:RasaItem7) contains 38 ingots.
Is in <ore:deltarising:materialstats_durability-great>
Is in <ore:deltarising:materialstats_thermalresistance-great>
Is in <ore:deltarising:materialstats_hardness-great>
Is in <ore:deltarising:ingot>
```

That few tags can matches almost everything from various details and materials in my modpack.
Screenshots: http://imgur.com/a/03OzM

Can it be changed\fixed? =\

**Comment by modmuss50** [comment] 2016-03-09 12:40
It might have to be fixed in TabulaRasa, but I will take a look

**Comment by EverybodyLies** [comment] 2016-03-09 12:41
@modmuss50, I can test that oredict-tags on different ids, if you need it.

**Comment by modmuss50** [comment] 2016-03-09 12:43
I may be able to add a flag, to disbale ore dic for a certain recipe.

**Comment by EverybodyLies** [comment] 2016-03-09 12:43
It would be great. However, maybe you can change inputs type to IIngredient, that can contain IOreDictTag and IItemStack, and just verify input type (ore/item)?

**Comment by modmuss50** [comment] 2016-03-10 08:21
@EverybodyLies I saw you created a wiki page, we do have an offical wiki here: http://techreborn.ninja/
sadly is got nothing on it

**Comment by EverybodyLies** [comment] 2016-03-10 14:57
@modmuss50, sorry for creating empty wiki page. just thinking, its not possible (no permissions), but...

**Comment by modmuss50** [comment] 2016-03-10 21:54
Its not my thing to fix, the other mod is over registering its ores.

**Comment by EverybodyLies** [comment] 2016-03-11 07:43
@modmuss50, all 4 oredict-tags registered with MineTweaker. it can't be TabulaRasa. I'm sure. Also, it can't be error with ignoring metadata of item, because input slot shows different ids (`TabulaRasa:RasaItem4`, `TabulaRasa:RasaItem5`, `TabulaRasa:RasaItem7`) with various meta. As i tested, MineTweaker does not make mistakes when registering oredict in any recipes - when input is IItemStack or IOreDictEntry (or IIngredient).

For me, it only remains that it is grinder recipe input error. (And, if i adding recipe with IItemStack on input, i think that must don't use oredict tags.)

**Comment by EverybodyLies** [comment] 2016-03-11 07:58
@modmuss50, same thing happens with Industrial Blast Furnace. Rolling all items with at least one of maching tags.
http://i.imgur.com/t9gRN8L.png

**Comment by Prospector** [comment] 2016-03-11 07:59
Wait what's the problem exactly? I don't get it.

**Comment by EverybodyLies** [comment] 2016-03-11 08:00
@ProfessorProspector Input in recipe is Ingot with 4 different oredict-tags. Recipe uses all items, that have at least one maching tag, that is 100+ items.

In my modpack i use oredict-tags and MT scripts for add some stats to materials. 38 materials, each of them has 13 different items (dust, ingot, gear, etc.). Recipe input accidentally maching all of that.

**Comment by Prospector** [comment] 2016-03-11 08:03
The machine would need to check for ore tags, then iterate through every item in the game to find a matching tag, then add a recipe for it which I am fairly certain is not happening. I don't know how Tabula Rasa works but I'm fairly sure it's probably the cause. @modmuss50 any ideas?

**Comment by EverybodyLies** [comment] 2016-03-11 08:04
TabulaRasa dont have any oredict-tag mechanic. It can just add blank items. Ore registered with minetweaker script.

**Comment by Prospector** [comment] 2016-03-11 08:07
Oh. If I am understanding this correctly, your saying that if I give a dirt block the tag blockTest, and I give a stone block blockTest, and add a recipe for the dirt block in a grinder, then I would also be able to grind stone?

**Comment by EverybodyLies** [comment] 2016-03-11 08:07
I cant test it. Wait for a minute.

**Comment by EverybodyLies** [comment] 2016-03-11 08:12
@modmuss50, @ProfessorProspector  Ok, tested.

```
<ore:grindertest>.add(<minecraft:stone>);
<ore:grindertest>.add(<minecraft:dirt>);
grinder.addRecipe(<minecraft:cobblestone>, null, null, null, <minecraft:stone>, null, 100, 32);
blastFurnace.addRecipe(<minecraft:cobblestone>, null, <minecraft:stone>, null, 400, 128, 1000);
```

This script adding stone to cobblestone recipe, and grinder takes `<ore:stone>` and `<ore:grindertest>` as input. Same thing with Industial Blast Furnace.

**Comment by modmuss50** [comment] 2016-03-11 08:20
ok, I will take a look at it later

**Comment by modmuss50** [comment] 2016-03-28 18:37
I will fix this when we have MineTweaker for 1.9

**Comment by Prospector** [comment] 2016-03-28 19:06
This isn't just with minetweaker. Any recipe. For example, look at extractor recipes. Only ModBlocks.rubber_log was registered but you can use any logWood.

**Comment by modmuss50** [comment] 2016-03-28 19:08
yeah, it can be done in code, its a minetweaker issue.

**Comment by Prospector** [comment] 2016-03-28 19:11
? it's not minetweaker. this happens without minetweaker

**Comment by Prospector** [comment] 2016-03-28 19:16
This recipe is registered: 
![image](https://cloud.githubusercontent.com/assets/6166773/14087417/c8eb2fca-f4de-11e5-8c66-f83730bb7c00.png)

Yet any logWood works in the recipe:

![image](https://cloud.githubusercontent.com/assets/6166773/14087439/ea787a26-f4de-11e5-91a9-f03eeee54efc.png)

Not using minetweaker/crafttweaker.

**Comment by Prospector** [comment] 2016-05-09 04:11
This is still an issue

**Comment by Prospector** [comment] 2016-12-11 15:54
Still an issue as of 1.11

**Closed as completed** 2016-12-12 09:22 UTC
Labels: bug, critical
