### ISSUE TITLE
[1.11] Electronic Circuit and Battery box broken

### ISSUE THREAD

**Issue by codenamedonut** [TechReborn/TechReborn#862] opened 2016-12-21 08:49 UTC
Electronic Circuit is now uncaftable and JEI/NEI no longer show recipe.
Battery Box displays negative number when full.

**Comment by ChloeDawn** [comment] 2016-12-21 11:20
Missing recipe for electronic circuit is a duplicate of https://github.com/TechReborn/TechReborn/issues/859

**Closed as completed** 2016-12-21 11:22 UTC
