### ISSUE TITLE
ores not generating in BYG biomes in 1.18.1

### ISSUE THREAD

**Issue by Chuunkyz** [TechReborn/TechReborn#2766] opened 2022-01-22 14:09 UTC
ores from this mod are inexistant in byg biomes and all modded biomes using terrablender
however some other ores such as indrev or ae2 work

**Comment by xanthian** [comment] 2022-01-22 14:54
duplicate of #2701

**Comment by Chuunkyz** [comment] 2022-01-22 21:56
not really a duplicate

**Comment by xanthian** [comment] 2022-01-22 21:59
same issue impacts all 3 biome mod types. so it is.
theres a PR on MI git to fix it, but needs some work.
hopefully @Technici4n can sort and copy it here ;)

**Comment by Technici4n** [comment] 2022-01-23 09:44
I want this to be fixed in fabric itself.

**Comment by xanthian** [comment] 2022-01-23 11:05
is anyone working on it ?

**Comment by aria1th** [comment] 2022-01-23 18:03
quick fix for it is using this instead: 
`	OVERWORLD(BiomeSelectors.foundInTheNether().negate().and(BiomeSelectors.foundInTheEnd().negate())),`
at TargetDimension.java.

vanilla ONLY supports nether biome modification (it considers its nether biome as modifed uhh) so currently there's no way to do it properly, also recent fabric api pr makes ore generation totally inaccessible so not a way to go...

The problem with it is vanilla biome registries are hardcoded, not dynamic, but nether is dynamic.

**Comment by Technici4n** [comment] 2022-01-24 11:00
There is an open fabric API PR to resolve this, if someone wants to help just go test that.

**Comment by aria1th** [comment] 2022-01-24 11:07
no, I just tested it and it totally disabled modded ore generation , even AE too, I guess you mean this : https://github.com/shartte/fabric/tree/move-biome-mods-into-server-ctor

Modded biomes sometimes does not register their dimension and directly plugs into chunkgenerator / noises...

**Comment by Technici4n** [comment] 2022-01-24 11:24
> no, I just tested it and it totally disabled modded ore generation , even AE too, I guess you mean this : https://github.com/shartte/fabric/tree/move-biome-mods-into-server-ctor

yes I meant that. If it didn't work please post a message on the PR otherwise it can't possibly be fixed.

**Comment by xanthian** [comment] 2022-01-31 10:40
New FAPI version fixes this :
![image](https://user-images.githubusercontent.com/7688001/151779219-9ddf50cb-52a5-4101-8e66-dd363f8e4a86.png)

A new world with 
FAPI 0.46.3
BYG 1.3.5.8
TR beta 7

**Closed as completed** 2022-01-31 11:08 UTC
Labels: bug
