### ISSUE TITLE
Cables Don't Work After World Reload Till Breaking & Placing Them All Again

### ISSUE THREAD

**Issue by ghost** [TechReborn/TechReborn#937] opened 2017-01-25 19:24 UTC
it got annoying now. i connected the mfsu to 5 machines with copper cable, and if i close my world then open again, mfsu has energy but machines don't get the energy from the MFSU. there are 500000 FE stored in MFSU, and it connected to the electric furnace with copper cable, but my electric furnace has 40 FE and doesn't smelt the inputs. but if i break ALL the cables, then place them all, it works. please fix this bug
using game 1.11.2 forge 2222 latest TR and RC

**Comment by modmuss50** [comment] 2017-01-25 19:25
Dupe of: https://github.com/TechReborn/TechReborn/issues/926

Please check the issue isnt already open before you open a new one.

**Closed as completed** 2017-01-25 19:25 UTC

**Comment by ghost** [comment] 2017-01-25 19:30
sry
