### ISSUE TITLE
[1.14.4] Fluid container textures are bugged with Optifine

### ISSUE THREAD

**Issue by erindal** [TechReborn/TechReborn#1839] opened 2019-09-11 18:15 UTC
![image](https://user-images.githubusercontent.com/12499779/64723367-68d19e00-d49e-11e9-982b-a399914fadc3.png)

As seen in REI, the textures bug out and form a weird triangle from the corner.

**Comment by drcrazy** [comment] 2019-09-12 14:00
What TR & RC version do you use? Any particular modpack?

Can't reproduce in dev env:

![image](https://user-images.githubusercontent.com/1382352/64790448-ca693980-d57e-11e9-88e3-e05290f6505b.png)

**Comment by modmuss50** [comment] 2019-09-12 14:02
This is an optifine issue I think.

**Comment by erindal** [comment] 2019-09-12 18:03
@modmuss50 Is correct, the bug is not present without optifine/optifabric.

**Comment by modmuss50** [comment] 2019-09-15 13:22
Im stuggling to fix this one, the best ive done is make it not render at all :D

I think this is something to do with optifine changing the vertex format when shaders are enabled.

**Comment by drcrazy** [comment] 2019-12-12 14:27
Won't fix. Looks like Fabric issue.

**Closed as completed by drcrazy** 2019-12-12 14:27 UTC
Labels: mod compat
