### ISSUE TITLE
1.11.2 Generators produce power without the need of fuel

### ISSUE THREAD

**Issue by leagris** [TechReborn/TechReborn#1037] opened 2017-04-06 22:39 UTC
### Versions:

* TechReborn-1.11.2-2.1.10.88-universal
* Minecraft Forge 13.20.0.2264
* teslafied-1.11-1.1.0.jar
* [Full mods list](https://github.com/Beyond-Reality/BeyondRealityModPack/blob/db318a77c8398d7a72559282bb59061bbf1d64a2/BR-1.11.2/modlist.md)

### Reproduce:

Place any TechReborn Generator against any Consumer device (electric furnace will do)
Device receive power from the Generator without inserting fuel into it.

### References:
https://github.com/Beyond-Reality/BeyondRealityModPack/issues/450

**Comment by modmuss50** [comment] 2017-04-08 14:11
Humm, could you get a screenshot or something, I cannot reproduce it.

**Comment by ghost** [comment] 2017-04-09 12:18
even better: a gif:
https://pbb.lc/daten/techreborn.gif
note that due to gif limitations when I hover over the power storage it looks like it's empty but that's just because of the gif limitations.

**Comment by leagris** [comment] 2017-04-09 18:19
Removing Tesla from modpack work-around disable this bug, but then TR power is only usable within TR.

**Comment by modmuss50** [comment] 2017-04-09 18:50
Ah, tesla. Ok that helps a lot thanks.

**Comment by Gorden211** [comment] 2017-04-10 22:55
Seems to be related to the issue I posted #978. I think it's the same bug.

**Comment by Prospector** [comment] 2017-04-10 23:38
Dupe of #978

**Closed as completed by Prospector** 2017-04-10 23:38 UTC
Labels: bug, unverified
