### ISSUE TITLE
[1.18.2] crash: Amount may not be negative, but it is: -8192

### ISSUE THREAD

**Issue by MSandro** [TechReborn/TechReborn#3135] opened 2023-05-09 05:25 UTC
**Describe the bug**
I am not sure if its a problem with TechReborn, maybe its on the side of the Spatial Harvesters Mod.
I have opened a issue there as well: https://github.com/Dunkmania101/SpatialHarvesters/issues/65

**Steps to Reproduce**
- Place a Spatial harvester and its Space Rippers around
- place a TechReborn energy Source on top, I've used a Creative Solar Panel
- exit world
- join world again
- crash

**Screenshots**
![image](https://user-images.githubusercontent.com/10937159/237001680-b424dbb4-b5b4-43cc-8452-68dcb725cddb.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.2
 - Mod Loader: Fabric
 
**Logs**
https://gist.github.com/MSandro/b8fd5d4d16327cc8806741b1f1cb9a3d

**Comment by MSandro** [comment] 2023-05-17 13:54
any help here?
I hope someon can help

**Comment by Ayutac** [comment] 2023-05-18 15:01
Duplicate of #3085

**Closed as not planned** 2023-05-18 15:01 UTC
Labels: bug, duplicate

**Comment by MSandro** [comment] 2023-05-18 17:35
https://github.com/Dunkmania101/SpatialHarvesters/issues/65#issuecomment-1553222009

**Comment by Ayutac** [comment] 2023-05-18 17:52
I know, I wrote that. It's not a TR bug.

**Comment by MSandro** [comment] 2023-05-18 17:54
Lol, didnt noticed that, i am sorry thanks for your help
