### ISSUE TITLE
BatBox (and possibly other ESUs) show Negative Energy Amount when Full

### ISSUE THREAD

**Issue by Spireshield** [TechReborn/TechReborn#637] opened 2016-06-07 13:59 UTC
Hello!
After updating today to the latest TechReborn and RebornCore, I've been playing around with it and noticed the Negative Energy Show is still here. What happens is, after it fills up and sometimes when filling up, shows a Negative EU Amount. EU can still be drawn, seems to be a Graphical Glitch.
![2016-06-07_09 58 04](https://cloud.githubusercontent.com/assets/16454255/15860285/61f42d04-2c96-11e6-832b-7199d2458e30.png)

It's not that big of an issue, but again, didn't see it on the "Issues" tab. If it's already been reported, sorry!

**Comment by modmuss50** [comment] 2016-06-07 13:59
Are you on a multiplayer server?

**Comment by Spireshield** [comment] 2016-06-07 14:00
Yes, I host my own Server, Is it somehow related?

**Comment by modmuss50** [comment] 2016-06-07 14:00
Dupe of #565

**Comment by modmuss50** [comment] 2016-06-07 14:01
Its known, I sort of know how to fix it

**Comment by Spireshield** [comment] 2016-06-07 14:01
Ah, okay. Sorry!

**Comment by Spireshield** [comment] 2016-06-07 14:01
Okay, cool. Thank You so much!

**Closed as completed by modmuss50** 2016-06-07 14:00 UTC
